# Generated by Django 5.2.5 on 2026-05-27 07:30

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_progress_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('total_questions_answered', models.PositiveIntegerField(default=0)),
                ('total_quizzes_completed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Guest User',
                'verbose_name_plural': 'Guest Users',
            },
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=0, editable=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quiz Category',
                'verbose_name_plural': 'Quiz Categories',
                'ordering': ['level', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('QUESTIONS_SOLVED', 'Questions Solved'), ('MODEL_TESTS_TAKEN', 'Model Tests Taken'), ('PRACTICE_TIME_MINUTES', 'Practice Time (Minutes)'), ('QUIZ_ATTEMPTS', 'Quiz Attempts')], max_length=30)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Streak',
                'verbose_name_plural': 'Streaks',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('QUESTION_ANSWERED', 'Question Answered'), ('QUIZ_COMPLETED', 'Quiz Completed'), ('MODEL_TEST_COMPLETED', 'Model Test Completed'), ('PRACTICE_SESSION', 'Practice Session')], max_length=30)),
                ('activity_date', models.DateField(auto_now_add=True)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration of activity in minutes', null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-activity_time'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('target_type', models.CharField(choices=[('QUESTIONS_SOLVED', 'Questions Solved'), ('MODEL_TESTS_TAKEN', 'Model Tests Taken'), ('PRACTICE_TIME_MINUTES', 'Practice Time (Minutes)'), ('QUIZ_ATTEMPTS', 'Quiz Attempts')], max_length=30)),
                ('total_target', models.PositiveIntegerField(default=0)),
                ('total_achieved', models.PositiveIntegerField(default=0)),
                ('days_completed', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Weekly Progress',
                'verbose_name_plural': 'Weekly Progress',
                'ordering': ['-week_start_date', 'target_type'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='savedquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('QUESTIONS_SOLVED', 'Questions Solved'), ('MODEL_TESTS_TAKEN', 'Model Tests Taken'), ('PRACTICE_TIME_MINUTES', 'Practice Time (Minutes)'), ('QUIZ_ATTEMPTS', 'Quiz Attempts')], max_length=30)),
                ('target_value', models.PositiveIntegerField(help_text='Target value (e.g., 50 questions, 2 tests, 120 minutes)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to=settings.AUTH_USER_MODEL)),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='api.guestuser')),
            ],
            options={
                'verbose_name': 'Daily Target',
                'verbose_name_plural': 'Daily Targets',
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('QUESTIONS_SOLVED', 'Questions Solved'), ('MODEL_TESTS_TAKEN', 'Model Tests Taken'), ('PRACTICE_TIME_MINUTES', 'Practice Time (Minutes)'), ('QUIZ_ATTEMPTS', 'Quiz Attempts')], max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('target_value', models.PositiveIntegerField(help_text='Target value for this date')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='api.guestuser')),
            ],
            options={
                'verbose_name': 'Daily Progress',
                'verbose_name_plural': 'Daily Progress',
                'ordering': ['-date', 'target_type'],
            },
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='savedquestion',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to='api.guestuser'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='quiz_attempt_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='quiz_attempt_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='saved_question_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='saved_question_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'question'), name='unique_user_question'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'question'), name='unique_guest_question'),
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.quizcategory'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='api.quizcategory'),
        ),
        migrations.AddField(
            model_name='streak',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='quiz_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.quizattempt'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='daily_target_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='daily_target_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'target_type'), name='unique_user_target_type'),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'target_type'), name='unique_guest_target_type'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='daily_progress_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='daily_progress_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'target_type', 'date'), name='unique_user_target_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'target_type', 'date'), name='unique_guest_target_date'),
        ),
        migrations.AlterUniqueTogether(
            name='quizcategory',
            unique_together={('name', 'parent')},
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='streak_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='streak_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'target_type'), name='unique_user_streak_type'),
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'target_type'), name='unique_guest_streak_type'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='user_activity_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='user_activity_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _connector='OR'), name='weekly_progress_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_user__isnull', False), _negated=True), name='weekly_progress_cannot_have_both_user_and_guest'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'week_start_date', 'target_type'), name='unique_user_week_target'),
        ),
        migrations.AddConstraint(
            model_name='weeklyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_user__isnull', False)), fields=('guest_user', 'week_start_date', 'target_type'), name='unique_guest_week_target'),
        ),
    ]
