# Generated by Django 5.2.8 on 2026-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_create_google_social_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBannerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main text of the banner', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle text below the main title', max_length=255, null=True)),
                ('button_text', models.CharField(help_text='Text to display on the action button', max_length=50)),
                ('batch_id', models.PositiveIntegerField(blank=True, help_text='Optional ID of the batch to promote. Tapping button opens this batch.', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='If multiple are active, the most recently updated one will be shown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Banner Notification',
                'verbose_name_plural': 'Home Banner Notifications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
