# Generated by Django 5.2.8 on 2026-06-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_affairs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyaffairsblock',
            new_name='monthly_aff_issue_i_d67b79_idx',
            old_name='monthly_aff_block_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyaffairsblock',
            new_name='monthly_aff_event_d_709986_idx',
            old_name='monthly_aff_date_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyaffairsissue',
            new_name='monthly_aff_source__4a0e0a_idx',
            old_name='monthly_aff_issue_idx',
        ),
    ]
