# Generated by Django 5.2.8 on 2026-06-06 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionlife', '0005_university_question_bank'),
        ('api', '0008_create_google_social_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batchcategory',
            new_name='admissionli_order_25427b_idx',
            old_name='admissionli_order_605803_idx',
        ),
        migrations.AlterUniqueTogether(
            name='savedquestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissionlife_quiz_attempts', to='api.guestuser'),
        ),
        migrations.AddField(
            model_name='savedquestion',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissionlife_saved_questions', to='api.guestuser'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissionlife_reported_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissionlife_quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissionlife_saved_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
